name: Deploy Front Botpress

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      - name: Clear and cache configuration and routes
        run: |
          php artisan config:clear
          php artisan route:clear
          php artisan config:cache
          php artisan route:cache

      - name: Verificar secrets
        run: |
          if [ -z "$DEPLOY_HOST" ]; then echo "DEPLOY_HOST está vacío"; else echo "DEPLOY_HOST está configurado"; fi
          if [ -z "$DEPLOY_USER" ]; then echo "DEPLOY_USER está vacío"; else echo "DEPLOY_USER está configurado"; fi
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}

      - name: Deploy to VPS
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: /var/www/laravel
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && git pull origin main && composer install --no-dev && php artisan config:cache"
